const data = {
    users: [
      {
        id: 1,
        name: "John",
        age: 25
      },
      {
        id: 2,
        name: "Jane",
        age: 30
      }
    ],
    recipes: [
          {
            name: "Hamburger",
            ingredients: ["Ground Beef", "Bun", "Lettuce", "Tomato", "Onion", "Cheese"],
            instructions: "Grill the patty, assemble with other ingredients, and serve.",
            isOKDiabetes: false,
            isOKHighPre: true,
            isOKHighCol: true,
            cookingTime: 20,
            mealKind: ["Main Meal"],
            cuisine: ["American"],
            diet: ["Normal"],
            tips: ["Serve with a side of French fries.", "Add pickles and ketchup for extra flavor."],
            interestingFacts: [],
            pictures: ["pictures/Hamburger1.jfif","pictures/hamburger2.jfif"
            ,"pictures/hamburger3.jfif"]
          },
          {
            name: "Pancakes",
            ingredients: ["Flour", "Milk", "Eggs", "Sugar", "Butter"],
            instructions: "Combine ingredients, cook on a griddle, and flip when golden brown.",
            isOKDiabetes: false,
            isOKHighPre: true,
            isOKHighCol: true,
            cookingTime: 15,
            mealKind: ["Breakfast"],
            cuisine: ["American"],
            diet: ["Normal"],
            tips: ["Serve with maple syrup and fresh fruits.", "Add chocolate chips for extra sweetness."],
            interestingFacts: [],
            pictures: ["pictures/Pancakes1.jfif","pictures/Pancakes2.jfif","pictures/Pancakes3.jfif"]
          },
          {
            name: "Mac and Cheese",
            ingredients: ["Elbow Macaroni", "Cheddar Cheese", "Milk", "Butter"],
            instructions: "Cook pasta, melt cheese with milk and butter, and mix with cooked macaroni.",
            isOKDiabetes: false,
            isOKHighPre: true,
            isOKHighCol: true,
            cookingTime: 25,
            mealKind: ["Main Meal"],
            cuisine: ["American"],
            diet: ["Normal"],
            tips: ["Top with breadcrumbs and bake for a crispy crust.", "Add cooked bacon for a smoky twist."],
            interestingFacts: [],
            pictures: ["pictures/macCheese1.jfif","pictures/macCheese2.jfif","pictures/macCheese3.jfif"]
          },
          {
            name: "Chicken Wings",
            ingredients: ["Chicken Wings", "Hot Sauce", "Butter", "Salt"],
            instructions: "Bake the chicken wings, toss with hot sauce and butter, and serve.",
            isOKDiabetes: false,
            isOKHighPre: true,
            isOKHighCol: true,
            cookingTime: 40,
            mealKind: ["Main Meal", "Snack"],
            cuisine: ["American"],
            diet: ["Normal"],
            tips: ["Enjoy with celery and blue cheese dip.", "Adjust the spice level according to your preference."],
            interestingFacts: [],
            pictures: ["pictures/ChickenWings1.jfif","pictures/ChickenWings3.jfif","pictures/ChickenWings2.jfif"]
          },
          {
            name: "Apple Pie",
            ingredients: ["Apples", "Pie Crust", "Sugar", "Cinnamon"],
            instructions: "Slice apples, mix with sugar and cinnamon, and bake in a pie crust.",
            isOKDiabetes: false,
            isOKHighPre: true,
            isOKHighCol: true,
            cookingTime: 50,
            mealKind: ["Dessert"],
            cuisine: ["American"],
            diet: ["Normal"],
            tips: ["Serve with a scoop of vanilla ice cream.", "Add a sprinkle of nutmeg for extra warmth."],
            interestingFacts: [],
            pictures: ["pictures/ApplePie1.jfif","pictures/ApplePie2.jfif","pictures/ApplePie3.jfif"]
          },
          {
            name: "BBQ Ribs",
            ingredients: ["Pork Ribs", "BBQ Sauce", "Salt", "Pepper"],
            instructions: "Season the ribs, grill with BBQ sauce, and baste while cooking.",
            isOKDiabetes: false,
            isOKHighPre: true,
            isOKHighCol: true,
            cookingTime: 180,
            mealKind: ["Main Meal"],
            cuisine: ["American"],
            diet: ["Normal"],
            tips: ["Serve with coleslaw and cornbread.", "Slow cook for tender and flavorful meat."],
            interestingFacts: [],
            pictures: ["pictures/bbq1.jfif","pictures/bbq2.jfif","pictures/bbq3.jfif"]
    },
    {
      name: "Cheeseburger",
      ingredients: ["Ground Beef", "Bun", "Cheese", "Lettuce", "Tomato", "Onion"],
      instructions: "Grill the patty, melt cheese on top, and assemble with other ingredients.",
      isOKDiabetes: false,
      isOKHighPre: true,
      isOKHighCol: true,
      cookingTime: 20,
      mealKind: ["Main Meal"],
      cuisine: ["American"],
      diet: ["Normal"],
      tips: ["Add pickles and condiments of your choice.", "Grill the buns for a toasty texture."],
      interestingFacts: [],
      pictures: ["pictures/Cheeseburger1.jpg","pictures/Cheeseburger2.jpg"]
    },
    {
      name: "French Toast",
      ingredients: ["Bread", "Eggs", "Milk", "Sugar", "Cinnamon", "Butter"],
      instructions: "Whisk eggs, milk, sugar, and cinnamon, soak bread, and cook on a griddle.",
      isOKDiabetes: false,
      isOKHighPre: true,
      isOKHighCol: true,
      cookingTime: 15,
      mealKind: ["Breakfast"],
      cuisine: ["American"],
      diet: ["Normal","Vegetarian"],
      tips: ["Top with powdered sugar or maple syrup.", "Serve with fresh berries for a fruity twist."],
      interestingFacts: [],
      pictures: ["pictures/ClamChowder1.jpg","pictures/ClamChowder1.jpg","pictures/frenchToast.jpg"]
    },
    {
      name: "Tacos",
      ingredients: ["Ground Beef", "Taco Shells", "Lettuce", "Tomato", "Cheese", "Salsa"],
      instructions: "Cook the ground beef, assemble with other ingredients in taco shells, and serve.",
      isOKDiabetes: false,
      isOKHighPre: true,
      isOKHighCol: true,
      cookingTime: 25,
      mealKind: ["Main Meal"],
      cuisine: ["American"],
      diet: ["Normal","Dairy free"],
      tips: ["Add guacamole and sour cream for extra creaminess.", "Use soft tortillas for a different texture."],
      interestingFacts: [],
      pictures: ["pictures/Tacos1.jpg","pictures/Tacos2.jpg","pictures/Tacos3.jpg"]
    },
    {
      name: "Clam Chowder",
      ingredients: ["Clams", "Potatoes", "Bacon", "Onion", "Cream", "Butter"],
      instructions: "Saute bacon and onions, add clams, potatoes, and cream, and simmer until cooked.",
      isOKDiabetes: true,
      isOKHighPre: true,
      isOKHighCol: true,
      cookingTime: 45,
      mealKind: ["Soup"],
      cuisine: ["American"],
      diet: ["Normal"],
      tips: ["Serve with crusty bread for dipping.", "Garnish with parsley for a pop of color."],
      interestingFacts: [],
      pictures: ["pictures/cc1.jpg","pictures/cc1.jpg"]
    },
    {
      name: "Garden Salad",
      ingredients: ["Lettuce", "Tomato", "Cucumber", "Carrot", "Onion", "Dressing"],
      instructions: "Toss all the vegetables together, drizzle with dressing, and mix well.",
      isOKDiabetes: true,
      isOKHighPre: true,
      isOKHighCol: true,
      cookingTime: 10,
      mealKind: ["Salad"],
      cuisine: ["American"],
      diet: ["Vegetarian","Gluten free","Dairy free"],
      tips: ["Add croutons or nuts for extra crunch.", "Customize with your favorite vegetables."],
      interestingFacts: [],
      pictures: ["pictures/GardenSalad1.jpg","pictures/GardenSalad2.jpg"]
    },
    {
      name: "Chocolate Cake",
      ingredients: ["Flour", "Sugar", "Cocoa Powder"],
      instructions: "Mix all ingredients and bake at 350°F for 30 minutes.",
      isOKDiabets: false,
      isOKHighPre: true,
      isOKHighCol: true,
      cookingTime: 30,
      mealKind: ["Breakfast", "Snack"],
      cuisine: ["French"],
      diet: ["Normal","Nut free"],
      tips: ["Add a pinch of salt to enhance the chocolate flavor.", "Serve with a dollop of whipped cream."],
      interstingFacts: ["The first chocolate cake recipe dates back to 1764 in France."],
      pictures: ["pictures/choclateCake2.jfif",
            "pictures/choclateCake3.jfif"]
    },
    {
      name: "Croissant",
      ingredients: ["Flour", "Butter", "Sugar", "Yeast", "Salt"],
      instructions: "Mix the ingredients, fold in layers with butter, shape, let rise, and bake.",
      isOKDiabets: false,
      isOKHighPre: true,
      isOKHighCol: true,
      cookingTime: 180,
      mealKind: ["Breakfast", "Snack"],
      cuisine: ["French"],
      diet: ["Normal"],
      tips: ["Use cold butter for better flakiness.", "Brush with egg wash for a shiny crust."],
      interstingFacts: ["The origin of the croissant is often attributed to Vienna, although it became popular in France."],
      pictures: []
    },
    {
      name: "Ratatouille",
      ingredients: ["Eggplant", "Zucchini", "Bell Pepper", "Tomato", "Onion", "Garlic", "Olive Oil", "Herbs de Provence"],
      instructions: "Sauté the vegetables with herbs and olive oil until tender.",
      isOKDiabets: true,
      isOKHighPre: true,
      isOKHighCol: true,
      cookingTime: 45,
      mealKind: ["Main Meal"],
      cuisine: ["French"],
      diet: ["Vegetarian", "Gluten free","Vegan","Vegetarian","Nut free","Dairy free"],
      tips: ["Let the ratatouille sit for some time to develop the flavors.", "Serve with crusty bread or over rice."],
      interstingFacts: ["Ratatouille originated in the region of Provence, France."],
      pictures: []
    },
    {
      name: "Coq au Vin",
      ingredients: ["Chicken", "Bacon", "Mushrooms", "Onion", "Carrot", "Garlic", "Red Wine", "Chicken Broth", "Flour", "Thyme", "Bay Leaf"],
      instructions: "Sear chicken, cook bacon and vegetables, deglaze with wine, add broth and herbs, simmer until chicken is cooked.",
      isOKDiabets: true,
      isOKHighPre: true,
      isOKHighCol: true,
      cookingTime: 120,
      mealKind: ["Main Meal"],
      cuisine: ["French"],
      diet: ["Normal","Nut free"],
      tips: ["Use a good quality red wine for the best flavor.", "Garnish with fresh parsley before serving."],
      interstingFacts: ["Coq au Vin is a classic French dish that dates back to ancient times."],
      pictures: []
    },
    {
      name: "Lamb Navarin",
      ingredients: ["Lamb Shoulder", "Onion", "Carrot", "Celery", "Potato", "Garlic", "Tomato", "Chicken Broth", "Flour", "Thyme", "Rosemary"],
      instructions: "Sear lamb, cook vegetables, add tomato and broth, simmer with herbs until lamb is tender.",
      isOKDiabets: true,
      isOKHighPre: true,
      isOKHighCol: true,
      cookingTime: 150,
      mealKind: ["Main Meal"],
      cuisine: ["French"],
      diet: ["Normal"],
      tips: ["Trim excess fat from the lamb for a leaner dish.", "Serve with crusty bread or mashed potatoes."],
      interstingFacts: ["Navarin refers to a type of stew traditionally made with lamb in French cuisine."],
      pictures: []
    },
    {
      name: "Salade Niçoise",
      ingredients: ["Lettuce", "Tomato", "Tuna", "Green Beans", "Potato", "Egg", "Olives", "Anchovies", "Capers"],
      instructions: "Arrange the ingredients on a platter, add dressing, and toss lightly before serving.",
      isOKDiabets: true,
      isOKHighPre: true,
      isOKHighCol: true,
      cookingTime: 20,
      mealKind: ["Salad"],
      cuisine: ["French"],
      diet: ["Nut free"],
      tips: ["Use fresh and high-quality ingredients for the best taste.", "Drizzle the salad with extra virgin olive oil."],
      interstingFacts: ["Salade Niçoise is a specialty of the Mediterranean cuisine, particularly originating from Nice, France."],
      pictures: []
    },
    {
      name: "Bouillabaisse",
      ingredients: ["Fish", "Shrimp", "Mussels", "Onion", "Leek", "Fennel", "Garlic", "Tomato", "White Wine", "Fish Broth", "Saffron", "Thyme", "Bay Leaf"],
      instructions: "Sauté vegetables, add broth, wine, and herbs, cook fish and shrimp in the broth, add mussels, simmer until cooked.",
      isOKDiabets: true,
      isOKHighPre: true,
      isOKHighCol: true,
      cookingTime: 75,
      mealKind: ["Soup"],
      cuisine: ["French"],
      diet: ["Gluten free"],
      tips: ["Serve with toasted baguette slices and rouille sauce.", "Choose a variety of fish for a more flavorful bouillabaisse."],
      interstingFacts: ["Bouillabaisse is a traditional fish stew originating from the Provence region of France."],
      pictures: []
    },
    {
      name: "Gratin Dauphinois",
      ingredients: ["Potato", "Milk", "Cream", "Garlic", "Nutmeg", "Gruyère Cheese"],
      instructions: "Slice potatoes, simmer in milk and cream with garlic and nutmeg, layer in a baking dish, top with cheese, and bake until golden.",
      isOKDiabets: false,
      isOKHighPre: true,
      isOKHighCol: true,
      cookingTime: 60,
      mealKind: ["Side Dish"],
      cuisine: ["French"],
      diet: ["Vegetarian"],
      tips: ["Use starchy potatoes like Russet for a creamier gratin.", "Let the gratin rest for a few minutes after baking before serving."],
      interstingFacts: ["Gratin Dauphinois is a classic French dish originating from the Dauphiné region."],
      pictures: []
    },
    {
      name: "Ratatouille Tart",
      ingredients: ["Pie Crust", "Ratatouille (pre-cooked)", "Goat Cheese"],
      instructions: "Pre-bake the pie crust, spread ratatouille over the crust, crumble goat cheese on top, and bake until the cheese is golden and bubbly.",
      isOKDiabets: false,
      isOKHighPre: true,
      isOKHighCol: true,
      cookingTime: 45,
      mealKind: ["Main Meal"],
      cuisine: ["French"],
      diet: ["Vegetarian"],
      tips: ["You can make your own ratatouille or use store-bought for convenience.", "Serve the tart warm or at room temperature."],
      interstingFacts: ["Ratatouille tart is a unique twist on the traditional ratatouille dish."],
      pictures: []
    },
    {
      name: "Tarte Tatin",
      ingredients: ["Apple", "Pie Crust", "Butter", "Sugar", "Cinnamon"],
      instructions: "Caramelize apples with butter, sugar, and cinnamon, place in a baking dish, cover with pie crust, and bake until golden and bubbly.",
      isOKDiabets: false,
      isOKHighPre: true,
      isOKHighCol: true,
      cookingTime: 60,
      mealKind: ["Dessert"],
      cuisine: ["French"],
      diet: ["Normal"],
      tips: ["Invert the tart onto a plate after baking for the classic presentation.", "Serve with a scoop of vanilla ice cream or whipped cream."],
      interstingFacts: ["Tarte Tatin is a famous French upside-down caramelized apple tart."],
      pictures: []
    },
    {
      name: "French Onion Soup",
      ingredients: ["Onion", "Butter", "Flour", "Beef Broth", "White Wine", "Baguette", "Gruyère Cheese"],
      instructions: "Caramelize onions with butter, sprinkle with flour, deglaze with wine, add broth, simmer, top with toasted baguette slices and cheese, broil until cheese is melted and golden.",
      isOKDiabets: true,
      isOKHighPre: true,
      isOKHighCol: true,
      cookingTime: 75,
      mealKind: ["Soup"],
      cuisine: ["French"],
      diet: ["Gluten free"],
      tips: ["Use sweet onions like Vidalia for a milder flavor.","Be patient while caramelizing the onions for the best result."],
      interstingFacts: ["French Onion Soup, also known as Soupe à l'Oignon, is a classic French dish with a rich onion flavor."],
      pictures: []
    },
    {
      name: "Coq au Vin Blanc",
      ingredients: ["Chicken", "Bacon", "Mushrooms", "Onion", "Carrot", "Garlic", "White Wine", "Chicken Broth", "Flour", "Thyme", "Bay Leaf"],
      instructions: "Sear chicken, cook bacon and vegetables, deglaze with wine, add broth and herbs, simmer until chicken is cooked.",
      isOKDiabets: true,
      isOKHighPre: true,
      isOKHighCol: true,
      cookingTime: 120,
      mealKind: ["Main Meal"],
      cuisine: ["French"],
      diet: ["Normal"],
      tips: ["Use a good quality white wine for a lighter flavor.", "Garnish with fresh parsley before serving."],
      interstingFacts: ["Coq au Vin Blanc is a variation of the classic Coq au Vin, using white wine instead of red."],
      pictures: []
    },
    {
      name: "Quiche Lorraine",
      ingredients: ["Pie Crust", "Bacon", "Gruyère Cheese", "Eggs", "Cream", "Onion", "Nutmeg"],
      instructions: "Pre-bake the pie crust, cook bacon and onion, mix eggs, cream, cheese, nutmeg, and cooked bacon and onion, pour into the crust, and bake until set.",
      isOKDiabets: false,
      isOKHighPre: true,
      isOKHighCol: true,
      cookingTime: 50,
      mealKind: ["Main Meal"],
      cuisine: ["French"],
      diet: ["Normal"],
      tips: ["Serve the quiche warm or at room temperature.", "You can customize the ingredients by adding vegetables or herbs."],
      interstingFacts: ["Quiche Lorraine is a classic French savory tart originating from the Lorraine region."],
      pictures: []
    },
    {
      name: "Beef Bourguignon",
      ingredients: ["Beef", "Bacon", "Mushrooms", "Onion", "Carrot", "Garlic", "Red Wine", "Beef Broth", "Flour", "Thyme", "Bay Leaf"],
      instructions: "Sear beef, cook bacon and vegetables, deglaze with wine, add broth and herbs, simmer until beef is tender.",
      isOKDiabets: true,
      isOKHighPre: true,
      isOKHighCol: true,
      cookingTime: 180,
      mealKind: ["Main Meal"],
      cuisine: ["French"],
      diet: ["Normal","Dairy free","Gluten free"],
      tips: ["Use a good quality red wine for the richest flavor.", "Serve with crusty bread or mashed potatoes."],
      interstingFacts: ["Beef Bourguignon is a classic French dish from the Burgundy region, made famous by Julia Child."],
      pictures: []
    },
    {
      name: "Crème Brûlée",
      ingredients: ["Egg Yolks", "Sugar", "Cream", "Vanilla"],
      instructions: "Whisk egg yolks and sugar, heat cream and vanilla, temper the egg mixture, pour into ramekins, bake in a water bath, cool, and sprinkle with sugar then torch until caramelized.",
      isOKDiabets: false,
      isOKHighPre: true,
      isOKHighCol: true,
      cookingTime: 90,
      mealKind: ["Dessert"],
      cuisine: ["French"],
      diet: ["Normal"],
      tips: ["Use a kitchen torch or broiler to caramelize the sugar.", "Chill the crème brûlée before serving for the best texture."],
      interstingFacts: ["Crème Brûlée is a classic French dessert with a custard base and a caramelized sugar topping."],
      pictures: []
    }
  ]
  };